version: '3.5'

services:
    upms-server:
        build: ./server/
        image: idler41/upms-server:1.0
        container_name: upms-server
        hostname: upms-server
        restart: always
        environment:
            HTTP_PORT: 8080
            JAVA_OPTS: '-server
                        -Xss512k
                        -Xmx512M
                        -XX:+UseConcMarkSweepGC
                        -XX:+CMSParallelRemarkEnabled
                        -XX:+HeapDumpOnOutOfMemoryError
                        -XX:HeapDumpPath=/home/tomcat/apache-tomcat/logs'
        expose:
            - 8080
            - 8005
        volumes:
            - type: volume
              source: upms-server-logs
              target: /home/tomcat/apache-tomcat/logs
        networks:
            net-upms:
                aliases:
                    - upms.server.com
    upms-front:
        build: ../
        image: idler41/upms-front:1.0
        container_name: upms-front
        hostname: upms-front
        restart: always
        expose:
            - 80
        volumes:
            - type: volume
              source: upms-goaccess-html
              target: /usr/share/nginx/html/goaccess
        networks:
            net-dev:
                aliases:
                    - upms.front.com

    nginx-proxy:
        build: ./proxy/
        image: idler41/nginx-proxy:1.0
        container_name: nginx-proxy
        hostname: upms.proxy.com
        restart: always
        ports:
            - 80:80
        volumes:
            - type: volume
              source: nginx-proxy-logs
              target: /var/log/nginx
        networks:
            net-dev:
                aliases:
                    - upms.proxy.com

    goaccess-upms:
        build: ./goaccess/
        image: idler41/goaccess-upms:1.0
        container_name: goaccess-upms
        ports:
            - 7890:7890
        restart: always
        volumes:
            - type: volume
              source: nginx-proxy-logs
              target: /srv/logs
            - type: volume
              source: upms-goaccess-html
              target: /srv/report
            - type: volume
              source: upms-goaccess-data
              target: /srv/data

networks:
    net-dev:
        name: net-dev
volumes:
    upms-server-logs:
        name: upms-server-logs
    upms-goaccess-html:
        name: upms-goaccess-html
    upms-goaccess-data:
        name: upms-goaccess-data
    nginx-proxy-logs:
        name: nginx-proxy-logs
